### ISSUE TITLE
Connection to a remote Redis server

### ISSUE THREAD

**Issue by mattrcl** [ran-jit/tomcat-cluster-redis-session-manager#47]
Hello,

I'd like to implement jedis on an application that runs with Tomcat and Java,
My redis server is not on the same server that my application and, following the readme, I modified the file redis-data-cache.properties to indicate the IP of my redis server.
However, it seems that this configuration file is not read because the application logs throw me errors such as "java-error: Caused by:  redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379".

Can you please help me ?

Thanks in advance,
Matthieu

**Comment by ran-jit** [comment]
Hi @mattrcl,

I think the redis session manager is using the default configuration. It may not have the "catalina.base" system property or it may be due to an invalid Tomcat base location value. So please add/verify the below system property and restart the service.

catalina.base="TOMCAT_LOCATION"
example: env "catalina.base=/opt/tomcat" bash

I hope it helps!

Thanks!

**Comment by mattrcl** [comment]
Hello @ran-jit ,

Thanks for your help !
I managed to solve my problem, it was just a permission problem with the file redis-data-cache.properties which couldn't be read by Tomcat because it is launched with a non-root user.
Now it works with redis :-)

Have a nice day,
Matt
