### ISSUE TITLE
version2.0 has a error in tomcat7 and jdk8

### ISSUE THREAD

**Issue by freeflyfree** [ran-jit/tomcat-cluster-redis-session-manager#6]

**Comment by freeflyfree** [comment]
This version2.0 is error  in tomcat7 and jdk8 
noSushMethod tomcat.request.session.redis.SessionManager.getContext()Lorg/apache/c

**Comment by ran-jit** [comment]
Hi @freeflyfree,

I've tested the same in Tomcat7 with JDK8, working fine as expected.

Is possible to share the log stacktrace here for further investigation.

Thanks!

**Comment by ran-jit** [comment]
@freeflyfree is any update ?

**Comment by ran-jit** [comment]
Hi @freeflyfree,

I identified the  issue (noSushMethod tomcat.request.session.redis.SessionManager.getContext()Lorg/apache/c) in 2.0 and fixed.

The fix is available in 2.2.1 release. (Release 2.0.1: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.1)

Please revert if any issues.

Thanks!
