### ISSUE TITLE
setMaxInactiveInterval bug

### ISSUE THREAD

**Issue by liushengyi** [ran-jit/tomcat-cluster-redis-session-manager#8]
The method "setMaxInactiveInterval" of session is not effective.

**Comment by ran-jit** [comment]
Hi @liushengyi,

Sorry for the delayed response.

I'm working on it, will update you as early as possible.

Thanks,
\ Ranjit

**Comment by ran-jit** [comment]
Hi @liushengyi,

I've identified the reported issue and fixed in the latest version.

The fix is available in 2.0.2 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.2). I request you to kindly upgrade your session manager from version x to 2.0.2.

Please revert if any issues.

Thanks!

**Comment by liushengyi** [comment]
@ran-jit 
Thanks for reply.
I will try it.

**Comment by ran-jit** [comment]
Hi @liushengyi,

Any update..? I hope the changes are working fine as expected. Please revert back..

Thanks,
